/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Vista.java
 *
 * Created on 13/03/2013, 06:16:03 AM
 */

package hebraenjava;

import java.awt.event.KeyEvent;

/**
 *
 * @author Admin
 */
public class Vista extends javax.swing.JFrame {

    /** Creates new form Vista */
    HebraMusica Hebra;
    Thread Threads;
    public Vista() {
        initComponents();
        Hebra = new HebraMusica();
        Threads = new Thread(Hebra);
        Threads.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bob = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fantasma");
        setMinimumSize(new java.awt.Dimension(550, 366));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        Bob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hebraenjava/fantasma.png"))); // NOI18N
        getContentPane().add(Bob);
        Bob.setBounds(200, 210, 65, 51);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hebraenjava/abandonado.jpg"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(540, 330));
        jLabel1.setMinimumSize(new java.awt.Dimension(540, 330));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        switch(evt.getKeyCode()){
            case KeyEvent.VK_UP:
                    Bob.setLocation(Bob.getX(),Bob.getY()-1);
                    break;
            case KeyEvent.VK_DOWN:
                    Bob.setLocation(Bob.getX(),Bob.getY()+1);
                    break;
            case KeyEvent.VK_RIGHT:
                    Bob.setLocation(Bob.getX()+1,Bob.getY());
                    break;
            case KeyEvent.VK_LEFT:
                    Bob.setLocation(Bob.getX()-1,Bob.getY());
                    break;
            default:
                    System.out.println("Tecla no reconocida");
                    break;
        }
    }//GEN-LAST:event_formKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bob;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
